#ifndef MYINCLUDE_H
#define MYINCLUDE_H

#include <QDebug>
#include <QProcess>
#include <QApplication>
#include <QDesktopWidget>
#include <windows.h>
#include <sddl.h>
#include <QPainter>
#include <QWidgetAction>
#include <QMenuBar>
#include <QMouseEvent>
#include <QPoint>
#include <QStyle>
#include <QSizeGrip>
#include <QCursor>
#include <QScreen>
#include <QPushButton>
#include <QToolButton>
#include <QMenu>
#include <QLabel>
#include <QLineEdit>
#include <QTableWidgetItem>
#include <QTableWidget>
#include <QHeaderView>
//#include <QNetworkAccessManager>
//#include <QNetworkReply>
//#include <QNetworkRequest>
//#include <QTcpSocket>
//#include <QWebSocket>
#include <QUrlQuery>
#include <QUrl>
#include <QString>
#include <QTimer>
#include <QDateTime>
#include <QJsonObject>
#include <QJsonDocument>
#include <QJsonArray>
#include <QGroupBox>
#include <QComboBox>
#include <QListView>
#include <QTimer>
#include <QHBoxLayout>
#include <QVBoxLayout>
#include <QFile>

#endif // MYINCLUDE_H
